[manager]
ratio = [3, 5, 7]

[opener]
edit = [
	{ run = 'hx "$@"', block = true, for = "unix" },
	{ run = "hx %*",   block = true, for = "windows" },
]

[open]
prepend_rules = [
	{ name = "*.svg", use = "edit" }
]
