[mgr]
ratio = [3, 5, 7]

[opener]
edit = [
	{ run = '$EIDTOR "$@"', block = true, for = "unix" },
	{ run = "%EDITOR% %*",   block = true, for = "windows" },
]

[open]
prepend_rules = [
	{ name = "*.svg", use = "edit" }
]
